#pragma once
#include <tchar.h>
#include <windows.h>
#include <WinUser.h>
#include <d3d11.h>
#include <ImGui/imgui.h>
#include <ImGui/imgui_internal.h>
#include <ImGui/imgui_impl_win32.h>
#include <ImGui/imgui_impl_dx11.h>
#include "GuiData.hpp"
